export const predefinedColors = [
    { name: 'White', code: '#ffffff' },
    { name: 'Grey', code: '#a2a9ad' },
    { name: 'Black', code: '#0D131A' },
    { name: 'Dark Grey', code: '#373a36' },
    { name: 'Brown', code: '#513629' },
    { name: 'Vegas Khaki', code: '#d0b787' },
    { name: 'Metallic Gold', code: '#85714D' },
    { name: 'Navy Blue', code: '#12284b' },
    { name: 'Forest Green', code: '#114734' },
    { name: 'Kelly Green', code: '#007940' },
    { name: 'Deep Teal ┈┈┈┈ Philly Eagles', code: '#006271' },
    { name: 'Light Teal ┈┈┈┈ Miami Dolphins', code: '#00b1bd' },
    { name: 'Nike Carolina', code: '#6fa2e4' },
    { name: 'Hopkins Blue', code: '#418fde' },
    { name: 'Nike Cobalt ┈┈┈┈ Duke', code: '#174293' },
    { name: 'Cascade Carolina', code: '#6dd6ff' },
    { name: 'Seafoam ┈┈┈┈ Sweetlax', code: '#80fff3' },
    { name: 'Lime Green ┈┈┈┈ True', code: '#93d500' },
    { name: 'Electric Green ┈┈┈┈ 802', code: '#03db48' },
    { name: 'Athletic Gold ┈┈┈┈ Packers', code: '#ffb71b' },
    { name: 'Yellow', code: '#fff200' },
    { name: 'Nike Orange', code: '#ee3724' },
    { name: 'Cascade Orange', code: '#ff5219' },
    { name: 'Tennesee Orange', code: '#FF8200' },
    { name: 'Purple ┈┈┈┈ LSU', code: '#592d82' },
    { name: 'Hot Pink', code: '#f732a1' },
    { name: 'Light Pink', code: '#ffa5d8' },
    { name: 'Burgundy', code: '#6e0624' },
    { name: 'Deep Burgundy', code: '#50131f' },
    { name: 'Crimson ┈┈┈┈ Harvard', code: '#A41034' },
    { name: 'Scarlet Red ┈┈┈┈ Rutgers', code: '#d00120' },
    { name: 'Texas Orange', code: '#CD5A13' },
];